# Generated by Django 5.2.4 on 2025-07-13 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('calories', models.IntegerField()),
                ('vegan', models.BooleanField(default=False)),
                ('gluten_free', models.BooleanField(default=False)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('retail_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='dish_pictures/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dessert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('calories', models.IntegerField()),
                ('vegan', models.BooleanField(default=False)),
                ('gluten_free', models.BooleanField(default=False)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('retail_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='dish_pictures/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('calories', models.IntegerField()),
                ('vegan', models.BooleanField(default=False)),
                ('gluten_free', models.BooleanField(default=False)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('retail_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='dish_pictures/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FirstCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('calories', models.IntegerField()),
                ('vegan', models.BooleanField(default=False)),
                ('gluten_free', models.BooleanField(default=False)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('retail_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='dish_pictures/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SecondCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('calories', models.IntegerField()),
                ('vegan', models.BooleanField(default=False)),
                ('gluten_free', models.BooleanField(default=False)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('retail_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='dish_pictures/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Food5_app.bread')),
                ('dessert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Food5_app.dessert')),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Food5_app.drink')),
                ('first_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Food5_app.firstcourse')),
                ('second_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Food5_app.secondcourse')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('gotten_date', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Food5_app.customer')),
                ('menus', models.ManyToManyField(to='Food5_app.menu')),
            ],
        ),
    ]
