# Generated by Django 5.2.4 on 2025-07-22 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food5_app', '0001_initial'),
        ('app_dessert', '__first__'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='dessert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_dessert.dessert'),
        ),
        migrations.RemoveField(
            model_name='menu',
            name='first_course',
        ),
        migrations.DeleteModel(
            name='Dessert',
        ),
        migrations.DeleteModel(
            name='FirstCourse',
        ),
    ]
