# Generated by Django 5.2.4 on 2025-07-22 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food5_app', '0001_initial'),
        ('app_Bread', '__first__'),
        ('app_first_course', '__first__'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='bread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Bread.bread'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='first_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_first_course.firstcourse'),
        ),
        migrations.DeleteModel(
            name='Bread',
        ),
        migrations.DeleteModel(
            name='FirstCourse',
        ),
    ]
