# Generated by Django 5.2.4 on 2025-07-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food5_app', '0001_initial'),
        ('app_menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='drink',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='bread',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='dessert',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='first_course',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='second_course',
        ),
        migrations.AlterField(
            model_name='order',
            name='menus',
            field=models.ManyToManyField(to='app_menu.menu'),
        ),
        migrations.DeleteModel(
            name='Drink',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='SecondCourse',
        ),
    ]
