# Generated by Django 5.2.4 on 2025-07-23 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Food5_app', '0002_remove_menu_drink_remove_menu_bread_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
