# Generated by Django 5.2.4 on 2025-07-23 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Food5_app', '0003_delete_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
