from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import SecondCourseViewSet

# Router automatically creates URL routes for the ViewSet
router = DefaultRouter()
router.register(r'second-courses', SecondCourseViewSet)

# Include all the routes generated by the router
urlpatterns = [
    path('', include(router.urls)),
]
