# Generated by Django 5.2.4 on 2025-07-22 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirstCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('calories', models.IntegerField()),
                ('vegan', models.BooleanField(default=False)),
                ('gluten_free', models.BooleanField(default=False)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('retail_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='dish_pictures/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
