# Generated by Django 5.2.4 on 2025-07-22 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_Bread', '0001_initial'),
        ('app_dessert', '0001_initial'),
        ('app_drink', '__first__'),
        ('app_first_course', '0001_initial'),
        ('app_second_course', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Bread.bread')),
                ('dessert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_dessert.dessert')),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_drink.drink')),
                ('first_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_first_course.firstcourse')),
                ('second_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_second_course.secondcourse')),
            ],
        ),
    ]
